### ISSUE TITLE
Task 6: Develop GeoWave heatmap process using statistics spatial binning

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#10]
Epic: https://github.com/mzagorskirs/geowave/issues/3

**Comment by mzagorskirs** [comment]
Definition of done:

- [x] The statistics queries will be pre-computed and cannot be filtered in GeoServer like the aggregation query results can be.
- [x] Create a count statistic.
- [x] Create a field sum statistic.

**Comment by mzagorskirs** [comment]
If the statistic (e.g. count or field sum) is not available, the equivalent aggregation metric will be computed on-the-fly and render the heatmap; and the statistic will be generated and added to the datastore at the same time for future use.

**Comment by mzagorskirs** [comment]
This first recording shows how the count aggregations are queried as default because the count statistics are not yet available (statistics must be pre-calculated, whereas aggregations can be queried/calculated on-the-fly).  See the sample geojson output files generated that represent the centroid of the GeoHash cell (precision 4) and the count value of hail events per GeoHash cell.  The count aggregations are used as default when the statistics are not available.  In this case, I set up the statistics to be calculated as the aggregations are queried, so that the statistics can be used in future.

When zooming in on the heatmap in the GeoServer UI, the count statistics are now being utilized (as can be seen with the generated geojson output files representing the centroid of the GeoHash cell and the count statistic value of hail events per GeoHash cell).  Notice that the count aggregation and count statistic values (located at the end of the geojson filename) match, as is expected.  

Also, notice as the heatmap is zoomed in further, the centroid of the GeoHash grid cell becomes more defined.

**Note:** the geojson output files are for testing and accuracy verification purposes only; they will not be part of the final tool functionality.

https://user-images.githubusercontent.com/43011672/162253932-4838f2d3-6a6d-4333-b6cb-9607696369a7.mp4

**Comment by mzagorskirs** [comment]
This second recording show the equivalent for field sum aggregations (used initially as the default to render the heatmap) and the field sum statistic (used subsequently after being calculated).  Notice that the field sum values (located at the end of the output geojson filenames) match between the field sum aggregation and statistic (in a few cases, the statistic shows a bit more decimal place accuracy).  The field in this case was the "SIZE" field of the hail dataset which is the size of the hail in each instance.  The field sum aggregation and statistic indicate the cumulative size of the hail per GeoHash grid cell (this is just an example, an average hail size would actually be more meaningful :smiley: ).

Also, notice as the heatmap is zoomed in further, the centroid of the GeoHash grid cell becomes more defined.

https://user-images.githubusercontent.com/43011672/162254775-aa87c926-6a27-428a-bd3d-aaa42cd3c71e.mp4

**Comment by rfecher** [comment]
approved
