### ISSUE TITLE
Task 8: Auto-select optimal Geohash precision

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#11]
Epic: https://github.com/mzagorskirs/geowave/issues/3

- add in code to auto-select the Geohash precision based on the Geohash envelope, pixel width and height.
- for example, something similar to: [https://github.com/geotools/geotools/blob/main/modules/library/coverage/src/main/j[…]org/geotools/coverage/grid/io/AbstractGridCoverage2DReader.java](https://github.com/geotools/geotools/blob/main/modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/AbstractGridCoverage2DReader.java#L434-L517)

**Comment by mzagorskirs** [comment]
I developed an algorithm to automatically select an appropriate Geohash precision as a user zooms into their data/heatmap.

These following demo videos show a combination of how the SLD is used to change the parameters fed into the custom heatmap process, and also how the Geohash precision used increases as the user zooms into the data/heatmap.

Notice that the performance of the Geohash auto-selector algorithm is optimized and there is very little lag while the algorithm is selecting an appropriate precision level.  Also, notice that when a stastistic (e.g. CNT_STATS = count statistic or SUM_STATS = field sum statistic) do not yet exist in the datastore, the equivalent aggregation query is run by default while the statistic is calculated and added to the datastore in the background for each Geohash precision level as the user zooms in.  Only after the statistics are calculated and added to the datastore can they be utilized upon a UI refresh.  

The output geojson files show the increasing Geohash precision level, the query type, and the query value in their title for each Geohash bin.  The query values have been verified to be accurate.

**Note:** the geojson output files are for testing and accuracy verification purposes only; they will not be part of the final tool functionality.

https://user-images.githubusercontent.com/43011672/163426533-dc826348-a6bd-4bdd-84e8-080016c59cb7.mp4


https://user-images.githubusercontent.com/43011672/163426510-b00f5bbf-3362-416f-84cb-c7888d857a32.mp4


https://user-images.githubusercontent.com/43011672/163426521-fb8b58aa-d0d4-4db3-9d98-7fabda59a782.mp4

**Comment by rfecher** [comment]
approved
