### ISSUE TITLE
Task 7: Add more parameters to SLD for user preferences

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#13]
Epic: https://github.com/mzagorskirs/geowave/issues/3

Some parameters to add:
- [x] Option to run statistic upon initial heatmap render if the statistic does not already exist in datastore (otherwise, the render will be based on the equivalent aggregation query, by default).
-  Spatial binning type (S2, H3, or Geohash). -- this is extra and might not be added in this ticket, but rather in a future ticket; Geohash is the requested spatial binning strategy._
- [x] Field name to run statistics or aggregations on (weightAttr - this param existed but was not hooked up to custom heatmap process).
- [x] Query type options:
    - count aggregation (CNT_AGGR)
    - field sum aggregation (SUM_AGGR)
    - count statistics (CNT_STATS)
    - field sum statistics (SUM_STATS)
 - [x] Option to use spatial binning or the regular heatmap process.

**Comment by mzagorskirs** [comment]
Epic: https://github.com/mzagorskirs/geowave/issues/3

**Comment by mzagorskirs** [comment]
Parameters added to automatically update the query type and weightAttr for the custom heatmap process.  Demo videos showing the dynamic parameters being changed in the SLD file are posted here: https://github.com/mzagorskirs/geowave/issues/11

Here is a demo video of the `createStats` toggle.  Notice that if set to `false`, the count statistics are not generated and saved to the datastore and the default count aggregation query is used for multiple runs.  When the toggle is set to `true`, the count statistics are generated and saved to the datastore and the default count aggregation is used only on the first run as a default while the statistics are being generated and saved.  Upon subsequent runs, the statistics will be output.

Notes: 

- the toggle only works when the `queryType` is set to one of the statistics options (e.g. CNT_STATS or SUM_STATS).
- the geojson output files are for testing and accuracy verification purposes only; they will not be part of the final tool functionality.


https://user-images.githubusercontent.com/43011672/163452325-e2e7b3b7-e888-460a-9517-afca87b68947.mp4

**Comment by rfecher** [comment]
approved
