### ISSUE TITLE
Task 9: Add spatial constraints to the query builders

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#14]
Epic: https://github.com/mzagorskirs/geowave/issues/3

Add the spatial constraints using JTS geometry to all the aggregation and statistics query builders to tune runtime.

**Comment by mzagorskirs** [comment]
Spatial constraints have been added and tested to the aggregation query builders.  Spatial constraints were added and then removed from the statistics query builders due to decreased performance at runtime.  Could potentially be a bug in the pre-existing code; will need to look into why RocksDB is running slow with the spatial constraint for statistics queries.

**Comment by mzagorskirs** [comment]
The following two demo videos show the spatial constraint applied to the aggregation queries.  Notice that, as the user zooms into the data, the output geojson files for the new Geohash precision become fewer and fewer, till just one output geojson results for Geohash precision level 12.


https://user-images.githubusercontent.com/43011672/164247277-7c29881e-5beb-4253-8a4a-12043d4141b2.mp4


https://user-images.githubusercontent.com/43011672/164247286-dd150280-660b-4aca-b92d-b2175bf8a26f.mp4

**Comment by rfecher** [comment]
approved
