### ISSUE TITLE
Task 1: Spike/Learning - GeoServer and plugins

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#4]
Epic: https://github.com/mzagorskirs/geowave/issues/3

See Epic for task details.

**Comment by mzagorskirs** [comment]
Plugin developed that shifts the data.

Code reviewed and approved for the scope of this ticket.

**Comment by mzagorskirs** [comment]
Demo of the render-transform-shift code:

The first rendered dataset is the original, the second is the shifted dataset.
The code shifts any geometry with a positive ID by -0.24 DD in both latitude and longitude directions, and any negative ID by +0.24 DD in both latitude and longitude directions, thus creating a fuzzy letter E.


https://user-images.githubusercontent.com/43011672/158822743-0416a9b4-a449-409f-ad61-a6d506a58678.mp4

**Comment by rfecher** [comment]
approved
