### ISSUE TITLE
Task 2: Get GeoServer example of heatmap working using GDELT data

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#5]
Epic: https://github.com/mzagorskirs/geowave/issues/3

See Epic for task details.

Look at GeoServer example of heatmap and get it working using GDELT data, with the ultimate goal of writing own heatmap plugin in JAVA.

**Comment by mzagorskirs** [comment]
I altered and applied the GeoServer example of a heatmap to the GDELT data using `countryCode` as the weighted variable:

![image](https://user-images.githubusercontent.com/43011672/158885701-8823e616-f492-4711-a425-20b1cdfd9077.png)

**Comment by mzagorskirs** [comment]
Results approved.

**Comment by rfecher** [comment]
approved
