### ISSUE TITLE
Task 3 - Set up Integration Test for Heatmap SLD

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#6]
Epic: https://github.com/mzagorskirs/geowave/issues/3

Purpose: to start a test-driven development process for the GeoWave Heatmap.

Definition of done:
- an Integration test that will test the application of the Heatmap SLD to some created unit test data.

**Comment by mzagorskirs** [comment]
Integration Test reviewed; progress approved; task can be closed.

**Comment by mzagorskirs** [comment]
![image](https://user-images.githubusercontent.com/43011672/159523122-30736ce0-1807-40db-8ee1-5e19556fa49b.png)

**Comment by rfecher** [comment]
approved
