### ISSUE TITLE
Task 4: Port GeoTools Heatmap process and research spatial binning methods

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#7]
Epic: https://github.com/mzagorskirs/geowave/issues/3

1. Port over GeoTools version of HeatmapProcess and understand it then hook up as a GeoWave plugin.  :heavy_check_mark: 

2. Become familiar with these examples:
- https://github.com/locationtech/geowave/blob/master/examples/java-api/src/main/java/org/locationtech/geowave/examples/stats/SpatialBinningStatisticExample.java  :heavy_check_mark: 

- https://github.com/locationtech/geowave/blob/master/test/src/test/java/org/locationtech/geowave/test/basic/GeoWaveSpatialBinningStatisticsIT.java  :heavy_check_mark: 

- https://github.com/locationtech/geowave/blob/master/examples/java-api/src/main/java/org/locationtech/geowave/examples/aggregation/binning/SpatialBinningAggregationExample.java  :heavy_check_mark: 

- https://github.com/locationtech/geowave/blob/master/test/src/test/java/org/locationtech/geowave/test/basic/GeoWaveSpatialBinningAggregationIT.java  :heavy_check_mark:

**Comment by mzagorskirs** [comment]
Ported GeoTools Heatmap process passes unit tests and functions within GeoServer.

![image](https://user-images.githubusercontent.com/43011672/159777610-1b8ebd54-e392-4f8e-a593-bc4955c6539e.png)

Ported heatmap applied to Hail shapefile using SIZE as the weighted attribute:
![image](https://user-images.githubusercontent.com/43011672/159777971-1806a1d5-bdca-4571-b927-6de34b0d2df4.png)


Zoomed in:
![image](https://user-images.githubusercontent.com/43011672/159777841-0d3af927-8071-4e3c-b3a8-85f86d038308.png)

**Comment by mzagorskirs** [comment]
The ported GeoTools heatmap process will be used as the baseline.  The GeoWave version will be a customization of the GeoTools heatmap process.

**Comment by rfecher** [comment]
approved
